// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/1/2025, 8:29:12 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/toda/work/claude/first-speckit/article-platform/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/toda/work/claude/first-speckit/article-platform/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/toda/work/claude/first-speckit/article-platform/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/toda/work/claude/first-speckit/article-platform/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/toda/work/claude/first-speckit/article-platform/plugins/**/*.{js,ts,mjs}","/home/toda/work/claude/first-speckit/article-platform/composables/**/*.{js,ts,mjs}","/home/toda/work/claude/first-speckit/article-platform/utils/**/*.{js,ts,mjs}","/home/toda/work/claude/first-speckit/article-platform/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/toda/work/claude/first-speckit/article-platform/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/toda/work/claude/first-speckit/article-platform/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/toda/work/claude/first-speckit/article-platform/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;